### PR TITLE
Fix "function" documentation typos

### PR DESCRIPTION
**Pull request by berkus**

### CODE REVIEW

**Comment by sagiegurari** [comment]
@berkus thanks a lot. ya, i really need to improve there :)
That file is auto generated, can you please update:
duckscript_sdk/src/sdk/std/flowcontrol/function/help.md
and than run
```sh
cargo make --no-workspace workspace-docs
```
and update the PR?

**Comment by berkus** [comment]
Yup, gimme a bit of time.

**Comment by berkus** [comment]
@sagiegurari done, fixed couple other typos while at it.

If I run into anything else I'll open another PR, so far it looks good :)

And thanks to duckscript (and cargo-make) [my tests are now running cross-platform](https://github.com/metta-systems/vesper/pull/10/) :)

**Comment by sagiegurari** [comment]
Thanks a lot for the PR, and please open additional ones when you do find something :)

**Pull request merged**
