### PR TITLE
New hex_decode and hex_encode command #165

### PR DESCRIPTION
**Pull request by umaYnit**

### CODE REVIEW

**Comment by sagiegurari** [comment]
This is super great.
1. can you add those to: https://github.com/sagiegurari/duckscript/blob/master/duckscript_sdk/src/sdk/std/math/mod.rs so they will be available?
2. can you also write tests in duckscript to test your new functions and put them in:
https://github.com/sagiegurari/duckscript/tree/master/test/std/math

**Comment by umaYnit** [comment]
Ok, I will modify it now

**Comment by umaYnit** [comment]
Should I add a format parameters for converting decimal to hexadecimal?

**Comment by sagiegurari** [comment]
anything that you think is useful

**Comment by umaYnit** [comment]
I have  no good ideas for parameters 😢

**Comment by sagiegurari** [comment]
not a must. can always add later if needed.

**Comment by sagiegurari** [comment]
@umaYnit i would really love to push this one, when can you also add it to the mod.rs and write few duckscript tests?

**Comment by umaYnit** [comment]
Glad you like it. I did it in the [second push](https://github.com/sagiegurari/duckscript/commit/b6e498279b18dedfca99b1f7164b4bb76187df09). Is there Something else I need to do?

**Comment by sagiegurari** [comment]
oops. missed it. will merge it soon. great work

**Comment by sagiegurari** [comment]
merging it. thanks a lot @umaYnit 
i'll be releasing it soon so you will have it available in cargo-make

**Pull request merged**
